'''389. Find the Difference

 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.'''


class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        ss = ''.join(sorted(s))
        ts = ''.join(sorted(t))
        
        for idx, m in enumerate(ss):
            if ts[idx] == m:
                continue
            else:
                return ts[idx]
        
        return ts[-1]

